SELECT nombre FROM producto ORDER BY nombre;
SELECT nombre, precio FROM producto ORDER BY nombre;
SELECT * FROM producto;
SELECT nombre, precio AS precio€, ROUND(precio*1.09,2) AS precio$ FROM producto ORDER BY nombre;
SELECT nombre AS "nom de producto", precio AS euros, ROUND(precio*1.09,2) AS dòlars FROM producto ORDER BY nombre;
SELECT UPPER(nombre) AS nombre, precio FROM producto ORDER BY nombre;
SELECT LOWER(nombre) AS nombre, precio FROM producto ORDER BY nombre;
SELECT nombre, UPPER(SUBSTRING(nombre,1,2)) AS "primeros 2 caracteres" FROM fabricante ORDER BY nombre;
SELECT nombre, ROUND(precio) AS precio FROM producto ORDER BY nombre;
SELECT nombre, TRUNCATE(precio,0) AS precio FROM producto ORDER BY nombre;
SELECT codigo_fabricante AS "codigo fabricante" FROM producto ORDER BY codigo_fabricante;
SELECT DISTINCT(codigo_fabricante) AS "codigo fabricante" FROM producto ORDER BY codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2 ORDER BY nombre;
SELECT producto.nombre AS "nombre producto", precio, fabricante.nombre AS "nombre fabricante" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY producto.nombre; 
SELECT producto.nombre AS "nombre producto", precio, fabricante.nombre AS "nombre fabricante" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre; 
SELECT producto.codigo AS "codigo producto", producto.nombre AS "nombre producto", producto.codigo_fabricante AS "codigo del fabricante", fabricante.nombre AS "nombre fabricante"FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre AS "nombre producto", precio, fabricante.nombre AS "nombre fabricante" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio LIMIT 1;
SELECT producto.nombre AS "nombre producto", precio, fabricante.nombre AS "nombre fabricante" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre AS "nombre producto" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo	WHERE fabricante.nombre = "Lenovo" ORDER BY producto.nombre;
SELECT producto.nombre AS "nombre producto" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo	WHERE fabricante.nombre = "Crucial" AND producto.precio>200 ORDER BY producto.nombre;
SELECT producto.nombre AS "nombre producto" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo	WHERE fabricante.nombre = "Asus" OR fabricante.nombre = "Hewlett-Packard" OR fabricante.nombre = "Seagate" ORDER BY producto.nombre;
SELECT producto.nombre AS "nombre producto" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo	WHERE fabricante.nombre IN ("Asus", "Hewlett-Packard", "Seagate") ORDER BY producto.nombre;
SELECT producto.nombre AS "nombre producto", precio FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo	WHERE RIGHT(fabricante.nombre,1) = 'e' ORDER BY producto.nombre;
SELECT producto.nombre AS "nombre producto", precio FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo	WHERE fabricante.nombre LIKE '%w%' ORDER BY producto.nombre;
SELECT producto.nombre AS "nombre producto", precio, fabricante.nombre AS "nombre fabricante" FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE precio>=180 ORDER BY precio DESC, producto.nombre;
SELECT fabricante.codigo, fabricante.nombre FROM fabricante JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre AS "nombre fabricante", producto.nombre AS "nombre producto" FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.codigo IS NULL;
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo");
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Lenovo"	ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = "Hewlett-Packard"	ORDER BY precio LIMIT 1;
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Asus") 	AND precio > (SELECT AVG(precio) FROM producto WHERE codigo_Fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Asus"));
